### ISSUE TITLE
New windows are not fullscreened because the extension only run at startup

### ISSUE THREAD

**Issue by McSinyx** [tazeat/AutoFullscreen#4]
I set `full-screen-api.ignore-widgets` so that toolbar is hidden on *fullscreen*. When I discovered this extension, I expect it works on all windows, but apparently it doesn't. I hope there is a way to fix this.

Here is a video footage:

[![thumb](https://i.ytimg.com/vi/9qIhQ6kPh40/0.jpg)](https://www.youtube.com/watch?v=9qIhQ6kPh40)

**Comment by tazeat** [comment]
That's correct this plugin only works on startup. If you wanted it to work on new windows, it wouldn't be too hard to do so. Simply add a callback to the browser.windows.onCreated.addListener(listener) function make the new window full sized on creation.

**Comment by tazeat** [comment]
Try adding this to the startup.js and repackaging if you want that behavior. 

browser.windows.onCreated.addListener((window) => {
  console.log("New window: " + window.id);
  browser.windows.update(window.id, {state: "fullscreen"});
});

**Comment by McSinyx** [comment]
Thanks for the prompt response. Originally I thought that it didn't run at window creation was a bug, but since it seems to be part of the feature design, feel free to close the issue when you feel it's the time to. For me the problem is solvved: Since I don't think I have the time pool to maintain a fork (given how often Firefox break addon compatibility lately), I guess I'd simply use `firefox --new-instance`.

Edit: either `firefox --new-instance` or `firefox --no-remote` works on GNU/Linux :disappointed:

**Comment by McSinyx** [comment]
Thanks to your suggestion, I've created [a fork that work exactly as I wanted](https://addons.mozilla.org/en-US/firefox/addon/alful/). I think the issue is solved by now.
