### ISSUE TITLE
Hiding mouse cursor?

### ISSUE THREAD

**Issue by ThomasFrickB** [tazeat/AutoFullscreen#6]
Hi,
I've just installed and configured your addon for our special purpose to have an alarm monitor, which shows us all alarm-related data in our depot ("we" means a red-cross organisation) - full screen works great. But: would it also be possible to hide the mouse cursor when in full screen? It's no big issue, just a little bit annoying having the useless mouse cursor on a clean screen, if you know what I mean. :)

**Comment by tazeat** [comment]
On Linux try Unclutter.

On Windows there used to be an option to hide after inactivity in Windows or there are a number of other lightweight tools to do so. Firefox does not have the ability to do it as far as I know.
