### ISSUE TITLE
Install offline

### ISSUE THREAD

**Issue by rickmoua** [tazeat/AutoFullscreen#8]
I have a computer with no Internet but has Firefox 78.0.2 esr.  Can the extension be loaded offline?

**Comment by brandoncasaba** [comment]
Sure, just download the XPI from the mozilla addons page.
https://addons.mozilla.org/firefox/downloads/file/1105247/auto_fullscreen-1.0.0.2-fx.xpi?src=dp-btn-primary

**Comment by tazeat** [comment]
Download the XPI file from the Firefox addons page:
https://addons.mozilla.org/firefox/downloads/file/1105247/auto_fullscreen-1.0.0.2-fx.xpi
